package string;
/*
 * Find the n’th term in Look-and-say (Or Count and Say) Sequence. The look-and-say sequence is the sequence of below integers: 
 * 1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, … 
 * How is above sequence generated? 
 * n’th term in generated by reading (n-1)’th term.
 * 
 * */
public class CountAndSay {
	
	 public String countAndSay(int n) {
		    int curr = 1;
		    String str = "1";
		    while (curr != n) {
		      StringBuilder sb = new StringBuilder();
		      int idx = 0;
		      int length = str.length();
		      while (idx < length) {
		        char c = str.charAt(idx);
		        int count = 0;
		        while (idx < length && str.charAt(idx) == c) {
		          idx++;
		          count++;
		        }
		        sb.append(count).append(c);
		      }
		      str = sb.toString();
		      curr++;
		    }
		    return str;
		  }
	public static void main(String[] args) {
		
		System.out.println(new CountAndSay().countAndSay(5));
	}

}
